[expect]
mode = "run"
exit = 0
stdout = "stdout.txt"
words = "program.words.say"
symbols = "program.symbols.say"
explain = "explain.txt"
hash = "b3:ho2lvgiccozgykzbq66zmt6fxjd5zpy4zx6mx36e3cc3smwjgilq"

