[expect]
mode = "run"
exit = 0
stdout = "stdout.txt"
words = "program.words.say"
symbols = "program.symbols.say"
explain = "explain.txt"
hash = "b3:3icysdjujdvda2562yiys5amg77cjgt4iu6rdzttklyzvuuokrwq"

