[expect]
mode = "run"
exit = 0
stdout = "stdout.txt"
words = "program.words.say"
symbols = "program.symbols.say"
explain = "explain.txt"
hash = "b3:s5ymahhi7v4bain75ko6zgkf727owfhatu5spxojxoskeblccypq"

