[expect]
mode = "run"
exit = 0
stdout = "stdout.txt"
words = "program.words.say"
symbols = "program.symbols.say"
explain = "explain.txt"
hash = "b3:qxybvmqcrweewpmwojpbenl7rg5jm3tdekxyohk6b3s3nuehm3ma"

