[expect]
mode = "test"
exit = 0
stdout = "stdout.txt"
words = "program.words.say"
symbols = "program.symbols.say"
explain = "explain.txt"
hash = "b3:wc4kh7zmr4aq5fu3dsoqu3eifxxv6yfj7lzljz5ujtjtbddchpuq"

