[expect]
mode = "run"
exit = 0
stdout = "stdout.txt"
words = "program.words.say"
symbols = "program.symbols.say"
explain = "explain.txt"
hash = "b3:i55oepy4bo73tjipy6lc6lwoaz6p2ayswbgveoxcinwtwsckgeqa"

